name: Build Release - Windows

on: workflow_dispatch

jobs:
    build-windows-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache Flutter dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.5.x # in ubuntu, pubspec.yaml can be used

            - name: Disable Analytics & Enable Windows Builds
              shell: pwsh
              run: |
                  flutter config --no-analytics
                  flutter config --enable-windows-desktop
                  flutter --version

            - name: Flutter doctor
              run: flutter doctor

            - name: Flutter pub get
              run: flutter pub get

            - name: Build Windows
              run: flutter build windows --release

            - name: Upload Windows build
              uses: actions/upload-artifact@v4
              with:
                  name: windows-build
                  path: build/windows/runner/Release/
