name: Build Flutter Windows App

on: workflow_dispatch

jobs:
    build-windows-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Cache Flutter installation
            - name: Cache Flutter
              uses: actions/cache@v4
              with:
                  path: C:\tools\flutter
                  key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-flutter-

            # - name: Setup Flutter
            #   run: choco install flutter --confirm --no-progress

            - name: Setup Flutter
              run: |
                  if (-Not (Test-Path C:\tools\flutter)) {
                    choco install flutter --confirm
                  }

            - name: Add Flutter to path
              run: $env:Path += ";C:\tools\flutter\bin"

            - name: Echo Version
              run: flutter --version

            - name: Disable Analytics
              run: flutter config --no-analytics

            - name: Check Flutter health
              run: flutter doctor

            # - name: Set up Flutter
            #   uses: subosito/flutter-action@v2
            #   with:
            #       channel: stable
            #       flutter-version: 'stable'

            # - name: Install dependencies
            #   run: flutter pub get

            # - name: Check Health
            #   run: flutter doctor

            # - name: Build Windows executable
            #   run: flutter build windows

            # - name: Upload build artifacts
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: windows-build
            #       path: build/windows/runner/Release/
