name: Clean Repository Artifacts

on:
    workflow_dispatch:

jobs:
    clean-artifacts:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Remove old artifacts
              uses: c-hive/gha-remove-artifacts@v1
              with:
                  age: '0 days'
